# Generated by Django 2.2.24 on 2023-05-11 20:18

from django.db import migrations


def update_new_building_in_flat(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Flat.objects.filter(construction_year__gte=2015).update(new_building=True)
    Flat.objects.filter(construction_year__lte=2015).update(new_building=False)


class Migration(migrations.Migration):
    dependencies = [
        ('property', '0004_auto_20230511_2301'),
    ]

    operations = [
        migrations.RunPython(update_new_building_in_flat),
    ]
