# Generated by Django 2.2.24 on 2023-05-13 22:15

from django.db import migrations


def set_owners(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    flats = Flat.objects.all()
    if flats.exists():
        for owner in flats.iterator():
            owner_name = owner.owner
            phonenumber = owner.owners_phonenumber
            pure_phonenumber = owner.owner_pure_phone
            Owner.objects.get_or_create(name=owner_name, phonenumber=phonenumber, pure_phone=pure_phonenumber)


class Migration(migrations.Migration):
    dependencies = [
        ('property', '0012_owner'),
    ]

    operations = [
        migrations.RunPython(set_owners),
    ]
