# Generated by Django 2.2.24 on 2023-05-13 22:30

from django.db import migrations


def add_flats(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    owners = Owner.objects.all()
    if owners.exists():
        for owner in owners.iterator():
            apartments = Flat.objects.filter(owner=owner.name)
            print(apartments)
            owner.flats.set(apartments)
            owner.save()


class Migration(migrations.Migration):
    dependencies = [
        ('property', '0014_auto_20230514_0145'),
    ]

    operations = [
        migrations.RunPython(add_flats),
    ]
